title: "Terraform OCI Container Instance with image deployed from OCIR"
description: "FoggyKitchen.com - Terraform OCI Container Instance with image deployed from OCIR."
stackDescription: "FoggyKitchen.com - Terraform OCI Container Instance with image deployed from OCIR."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - region
  - oci_service_gateway
  - network_cidrs

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - availablity_domain_name
  - enable_vault
  - vault_secret_id
  - ocir_user_name
  - ocir_user_password
  - ocir_namespace
  - show_advanced 

- title: "OCIR Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - ocir_repo_name
  - ocir_docker_repository

- title: "Container Instance Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - container_instance_shape
  - container_instance_shape_memory
  - container_instance_shape_ocpus

- title: "Network Optional Configuration"
  visible:
      and:
        - show_advanced
  variables:
  - enable_ephemeral_public_ip
  - enable_reserved_public_ip
  - nginx_port
  - enable_ssl
  - nginx_ssl_port
  - ssl_cert
  - ssl_key
  - enable_dns 
  - dns_domain
  - dns_a_record_ttl
  - enable_nsg
  
variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region where you deploy your Webserver"
    type: oci:identity:region:name
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment OCID"
    description: "Choose Comparment where you deploy your Webserver"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain"
    description: "Choose Availability Domain where K8S Nodes will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  enable_vault:
    type: boolean
    title: "Enable OCI Vault?"
    description: "Check if you want to use OCI Vault for OCIR username and password."
    visible: true
    default: false

  enable_vault_iam:
    type: boolean
    title: "Enable OCI Vault IAM?"
    description: "Check if you want to create IAM Dynamic Group and Policy for enabling Container Instances access OCI Vault."
    default: true 
    visible:
      and:
        - enable_vault

  vault_secret_id:
    type: string
    required: true
    title: "OCI Vault Secret OCID"
    description: "OCI Vault Secret OCID consisting OCIR username and password"
    visible:
      and:
        - enable_vault

  ocir_user_name:
    type: string
    required: true
    title: "OCIR username"
    description: "Oracle Cloud Infrastructure Registry username (your OCI username)"
    visible:
      not:
        - enable_vault

  ocir_user_password:
    type: password
    required: true
    title: "OCIR user password"
    description: "Oracle Cloud Infrastructure Registry user password (your OCI user authtoken)" 
    visible:
      not:
        - enable_vault

  # Optional Configuration

  container_instance_shape:
    type: enum
    title: "Container Inastance Shape"
    description: "Choose a shape for your Container Instance"
    default: "CI.Standard.E4.Flex"
    required: false
    enum:
      - "CI.Standard.E4.Flex"
      - "CI.Standard.E3.Flex"


  container_instance_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Container Instance Shape Shape OCPUs"
    description: "Choose OCPUs for Container Instance Shape."

  container_instance_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Container Instance Shape Memory (GB)"
    description: "Choose number GB for Container Instance Memory."

  ocir_namespace:
    type: string
    title: "OCIR Namespace"
    description: "Choose OCIR Namespace."
    required: false
    visible:
      not:
        - enable_vault

  ocir_repo_name:
    type: string
    title: "OCIR Repo Name"
    description: "Choose OCIR Repo Name."
    required: false

  ocir_docker_repository:
    type: string
    title: "OCIR Docker Repository"
    description: "Choose OCIR Docker Repository."
    required: false

  enable_ephemeral_public_ip:
    type: boolean
    title: "Enable Public Ephemeral IP?"
    description: "Use Public Ephemeral IP Address for Container Instance"
    visible: true
    default: false
    
  enable_reserved_public_ip:
    type: boolean
    title: "Enable Public Reserved IP?"
    description: "Use Public Reserved IP Address for Container Instance"
    visible: true
    default: false

  nginx_port:
    type: number
    required: false
    minimum: 1
    maximum: 65535
    multipleOf: 1
    default: 80
    title: "NGINX Port in Container Instance"
    description: "Choose NGINX Port deployed in Container Instance."

  enable_ssl:
    type: boolean
    title: "Configure SSL for NGINX?"
    description: "Decide if you want to configure SSL fro NGINX."
    default: false
    required: false

  nginx_ssl_port:
    type: number
    required: false
    minimum: 1
    maximum: 65535
    multipleOf: 1
    default: 443
    title: "NGINX SSL Port in Container Instance"
    description: "Choose NGINX SSL Port deployed in Container Instance."
    visible:
      and:
        - enable_ssl

  ssl_cert:
    type: text
    required: false
    default: ""
    title: "SSL Certificate"
    description: "Paste here SSL Certificate File Content (fullchain.pem)."
    visible:
      and:
        - enable_ssl

  ssl_key:
    type: text
    required: false
    default: ""
    title: "SSL Certificate Key"
    description: "Paste here SSL Certificate Key File Content (privkey.pem)."
    visible:
      and:
        - enable_ssl

  enable_dns:
    type: boolean
    title: "Configure DNS Zone?"
    description: "Decide if you want to configure DNS Public Zone (only for Public Reserved IP)."
    visible: 
      and:
        - enable_reserved_public_ip
    default: false 
    required: false
  
  dns_domain:
    type: string
    required: true
    title: "DNS Domian Name"
    description: "Define DNS Domain name for DNS Management."
    visible: 
      and:
        - enable_dns
        - enable_reserved_public_ip

  dns_a_record_ttl:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 30
    title: "DNS A Record TTL"
    description: "Choose Time To Leave value for DNS A Record."
    visible:
      and:
        - enable_dns
        - enable_reserved_public_ip

  enable_nsg:
    type: boolean
    title: "Configure NSG?"
    description: "Decide if you want to configure Network Security Group (NSG)."
    default: false
    required: false
