title: "Terraform OCI Container Instance with image deployed from OCIR"
description: "FoggyKitchen.com - Terraform OCI Container Instance with image deployed from OCIR."
stackDescription: "FoggyKitchen.com - Terraform OCI Container Instance with image deployed from OCIR."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - region
  - oci_service_gateway
  - network_cidrs

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - availablity_domain_name
  - ocir_user_name
  - ocir_user_password
  - show_advanced 

- title: "OCIR Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - ocir_namespace
  - ocir_repo_name
  - ocir_docker_repository

- title: "Container Instance Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - container_instance_shape
  - container_instance_shape_memory
  - container_instance_shape_ocpus

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region where you deploy your Webserver"
    type: oci:identity:region:name
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment OCID"
    description: "Choose Comparment where you deploy your Webserver"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain"
    description: "Choose Availability Domain where K8S Nodes will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  ocir_user_name:
    type: string
    required: true
    visibile: true
    title: "OCIR username"
    description: "Oracle Cloud Infrastructure Registry username (your OCI username)" 

  ocir_user_password:
    type: password
    required: true
    visibile: true
    title: "OCIR user password"
    description: "Oracle Cloud Infrastructure Registry user password (your OCI user authtoken)" 

  # Optional Configuration

  container_instance_shape:
    type: enum
    title: "Container Inastance Shape"
    description: "Choose a shape for your Container Instance"
    default: "CI.Standard.E4.Flex"
    required: false
    enum:
      - "CI.Standard.E4.Flex"
      - "CI.Standard.E3.Flex"


  container_instance_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Container Instance Shape Shape OCPUs"
    description: "Choose OCPUs for Container Instance Shape."

  container_instance_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "Container Instance Shape Memory (GB)"
    description: "Choose number GB for Container Instance Memory."

  ocir_namespace:
    type: string
    title: "OCIR Namespace"
    description: "Choose OCIR Namespace."
    required: false

  ocir_repo_name:
    type: string
    title: "OCIR Repo Name"
    description: "Choose OCIR Repo Name."
    required: false

  ocir_docker_repository:
    type: string
    title: "OCIR Docker Repository"
    description: "Choose OCIR Docker Repository."
    required: false

  



